name: Generate Links

on:
  push:
    branches:
      - main
    paths:
      - 'public/cpp/*.cpp'

jobs:
  generate-links:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v2

      - name: Generate Links for Algorithms
        run: |
          # C++ ファイルの一覧を取得
          cpp_files=$(find public/cpp -name "*.cpp")

          # Layout.js に埋め込むリンクリストを生成
          echo "const algorithmLinks = [" > components/algorithmLinks.js
          for file in $cpp_files; do
            filename=$(basename "$file" .cpp)
            url="/cpp/$filename.cpp"
            echo "  { name: '$filename', url: '$url' }," >> components/algorithmLinks.js
          done
          echo "];" >> components/algorithmLinks.js
          echo "export default algorithmLinks;" >> components/algorithmLinks.js

      - name: コミットとプッシュ
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add components/algorithmLinks.js
          git commit -m "Auto-generate algorithm links"
          git push origin main
